### ISSUE TITLE
Crash when disconnecting.

### ISSUE THREAD

**Issue by CalebWhiting** [MrFast-js/Skyblock-Tweaks#5]
**Describe the bug**
Sometimes crash when pressing "disconnect" on game menu.

**To Reproduce**
Join Hypixel Skyblock
Move around a bit
Press ESC to open game menu
Press "Disconnect"

**Expected behavior**
Disconnect and return to main menu.

**Screenshots**
Nothing to see, game has crashed.

**Please complete the following information:**
 - OS: Linux/Kernel 6.11.2
 - Browser: N/A
 - Version: 1.0.2-BETA2

**Additional context**
It seems that it only happens after moving around in game for a few seconds or so, maybe giving some time for entities to appear, it looks like it's something to do with particles from the log.

Log: https://mclo.gs/3opj0HI

**Comment by MrFast-js** [comment]
This was fixed, in a commit already, next beta will have it fixed, hopefully by tonight it will be released

**Comment by MrFast-js** [comment]
https://github.com/MrFast-js/Skyblock-Tweaks/commit/c9a8052da73dd108448dd88a57ac4ec0f3e49b1d
